//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.01.14 at 11:25:02 PM EET 
//


package myxml;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for step complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="step">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="letter" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="xpos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="ypos" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *       &lt;attribute name="move" type="{http://www.w3.org/2001/XMLSchema}int" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "step", propOrder = {
    "letter",
    "xpos",
    "ypos"
})
public class Step {

    @XmlElement(required = true)
    protected String letter;
    protected int xpos;
    protected int ypos;
    @XmlAttribute(name = "move")
    protected int move;
    
    Step(){}

    public Step(int move, String letter, int xpos, int ypos) {
        this.letter = letter;
        this.xpos = xpos;
        this.ypos = ypos;
        this.move = move;
    }
    

    /**
     * Gets the value of the letter property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLetter() {
        return letter;
    }

    /**
     * Sets the value of the letter property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLetter(String value) {
        this.letter = value;
    }

    /**
     * Gets the value of the xpos property.
     * 
     */
    public int getXpos() {
        return xpos;
    }

    /**
     * Sets the value of the xpos property.
     * 
     */
    public void setXpos(int value) {
        this.xpos = value;
    }

    /**
     * Gets the value of the ypos property.
     * 
     */
    public int getYpos() {
        return ypos;
    }

    /**
     * Sets the value of the ypos property.
     * 
     */
    public void setYpos(int value) {
        this.ypos = value;
    }

    /**
     * Gets the value of the move property.
     * 
     * @return
     *     possible object is
     *     {@link int}
     *     
     */
    public int getMove() {
        return move;
    }

    /**
     * Sets the value of the move property.
     * 
     * @param value
     *     allowed object is
     *     {@link int }
     *     
     */
    public void setMove(int value) {
        this.move = value;
    }

}
